### ISSUE TITLE
Javascript Capstone - Kanban Board Review

### ISSUE THREAD

**Issue by NitBravoA92** [PabloBona/JavaScriptCapstone#21]
# ⭐Kanban Board - Request a Review 👨‍💻

## Project details 📃

- Link the Kanban Board: https://github.com/PabloBona/JavaScriptCapstone/projects/1
- Number of group members: **Two (2) members** 

# To the Reviewer
💝 I really thank 🙇‍♂️ you, dear code reviewer 👨‍🎨 for dedicating your precious 🥇 time ⌚ to check the PR 🧾 .

We kindly ask 🙏 dear reviewer 🤵 that if there is any kind of issue 🦯 in this project, please do list 📃 them in a descriptive 💡 manner and give your best suggestions 🎁 if needed.

If you think some issues are essential to be changed ♻️ please kindly contact 📞 us through Zoom or Slack, We are available on Microverse UTC-6 time zone.

**Comment by julie-ify** [comment]
## Hi @NitBravoA92 and @PabloBona,

Good job so far!

## Highlights!
- Descriptive tasks ✔️

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

# Status: Required Changes ♻️⛔️
- [ ] Kindly ensure all your tasks are assigned. This is what assigned tasks look like.

  ![andre-assigned](https://github.com/PabloBona/JavaScriptCapstone/assets/81468675/7ea307b3-73ae-4a15-bc9f-9485a156e356)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@julie-ify` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Shisui6** [comment]
Hi @NitBravoA92 and @PabloBona, 

# Approved 🪄
Your project is complete! There is nothing else to say other than... it's time to merge it 💎
Congratulations! 🎉 

## Highlights 🎯
- Kanban board setup properly ✅


## Optional suggestions 🪶

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code. Some of them were simply missed by the previous reviewer, and addressing them will really improve your application._

You can also consider the following:

N/A

Cheers and Happy coding!🍻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by NitBravoA92** [comment]
The Kanban board was successfully approved. ✅ The issue is now closed.
